name: Run Tests

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Run tests
        run: >
          dotnet test Calcpad.Tests
          --logger "console;verbosity=detailed"
          --logger "trx;LogFileName=test-results.trx"
          --results-directory ./test-results

      - name: Publish test results to summary
        uses: dorny/test-reporter@v3
        if: ${{ !cancelled() }}
        with:
          name: Unit Tests
          path: test-results/test-results.trx
          reporter: dotnet-trx
          use-actions-summary: true

